### ISSUE TITLE
Customer API todo list

### ISSUE THREAD

**Issue by TwoFistedJustice** [TwoFistedJustice/square-pie#142]
These bits need to be added to the Customer API

**Customer_List**
- [x] add endpoint with getter and private setter
- [x] add query param builders
- [x] add make() with references to query params builders

**Customer_Create**
- [x] <del>add make() with customer function which takes a customer object and passes it to the customer setter

**Customer_Delete**
- [x] add endpoint with getter and private setter
- [x] add query param builder for version
- [x] add make() with references to query params builders

**Customer_Update**
- [x] refactor version setter to check for presence of property and add it if it's not there (in case user just adds a customer object) 
- [x] add a 'customer' method to make which swaps in the customer object for the body (call body setter) 
- [x] Refactor body setter so it caches the version property if it is set and restores it. Or better yet, if feasible, have it iterate over the input and set the values on body while leaving the keys.
