### ISSUE TITLE
Order API todo LIst

### ISSUE THREAD

**Issue by TwoFistedJustice** [TwoFistedJustice/square-pie#144]
These bits need to be added to the Order API

**Docs**
- [x] consolidate Order API objects and requests into same set of tables
- [x] make a doc for using Order API Order_Search

**Order_Retrieve**

- [x] fix bug in array_concat - uses wrong length validator

**Order_Search**

- [x]  add a function to concat an array of location_ids - steal it from Order_Retrieve
- [x] Update help
- [x] add unit test

**Order_Pay**

- [x] add a function to concat an array of payment_ids - steal it from Order_Retrieve
- [x] Update help
- [x] add unit test

**Order_Line_Item**

- [x] make_modififier needs an 'add' method - see todo just above function

step 1 make_modifier sets the modify property
step 2 add the modify property to the modifiers array
