### ISSUE TITLE
Catalog_Item class todo

### ISSUE THREAD

**Issue by TwoFistedJustice** [TwoFistedJustice/square-pie#161]
### Catalog_Item class todo
- [x] item_options setter - change array length validator
- [x] set variations - arrayify
- [x] Modify constructor to take an ID as an argument, if none is provided, set it with nanoid. ~~If it changes later, iterate over the variations array and change all the item_id to match~~
- [x] modifier_list_info - object builder
