### ISSUE TITLE
Catalog_Search_Filter todo 

### ISSUE THREAD

**Issue by TwoFistedJustice** [TwoFistedJustice/square-pie#163]
### Catalog_Search_Filter todo 

- [x] builder fn for exact_query
- [x] builder fn for prefix_query
- [x] builder fn for range_query
- [x] builder fn for set_query?
- [x] builder fn for sorted_attribute_query // have the builder set ASC as default w opt to change
- [x] refactor fn for text_query 
- [x] refactor setter for text_query - make it the concat function? should push word onto array and limit to len 3 
- [x] create concat setter for text_query - limit to len 3  
- [x] remove text_query_add() - may make good main setter? 
- [x] make().object.types() - ref the enum in the enum folder
- [x] refactor the enum so it can chain with the rest of make()
- [x] add concat_object_types fn to super
