### ISSUE TITLE
Invoice Object todo

### ISSUE THREAD

**Issue by TwoFistedJustice** [TwoFistedJustice/square-pie#177]
Invoice Object Todo
- [x] change  #build_custom_field() to make
- [x] conslidate jsdocs for  make_custom_field()
- [x] accepted_payment_methods_enum - add true and false methods
- [x] refactor enums to return calling_this
- [x] Unit tests  
- [x] jsdocs
