### ISSUE TITLE
Shazam Refactor Todo List

### ISSUE THREAD

**Issue by TwoFistedJustice** [TwoFistedJustice/square-pie#203]
Swap argument order to reflect order of operations in

- [x] shazam_max_length
- [x] shazam_max_length_array
- [x] shazam_min_length
- [x] shazam_min_length_array
